### PR TITLE
fix: modernize the examples

### LINKED ISSUE #94: Websocket example doesn't appear to do anything
## Observed:
```
$ deno run --allow-net https://examples.deno.land/websocket.ts
$
```
(no output)

## Expected:
Logging about the socket readyState and a "ping" event echoed back.

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #94. Changed examples as needed to remove errors.

### CODE REVIEW

File: data/writing-files.ts [hunk 1]
```diff
@@ -28,20 +32,12 @@ const written = await file.write(bytes);
 console.log(`${written} bytes written.`);
 
 // A `file.write` returns the number of bytes written, as it might not write all
-// bytes passed. Use the `writeAll` utility from `std/streams` to make sure the
-// entire buffer is written.
-import { writeAll } from "$std/streams/write_all.ts";
-await writeAll(file, new TextEncoder().encode("World!"));
+// bytes passed. We can get a Writer insteda to make sure the entire buffer is written.
```
Comment (hashrock) [inline data/writing-files.ts:35]:
```suggestion
// bytes passed. We can get a Writer instead to make sure the entire buffer is written.
```

Comment (lino-levan) [reply data/writing-files.ts:35]: Nice catch!

**Review by hashrock — APPROVED** [review]
LGTM!
